food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    #/food/
    path('',views.IndexClassView.as_view(),name='index'),
    #/food/id
    path('<int:pk>/',views.DetaleClassView.as_view(),name='detail'),
    path('item/',views.item,name='item'),
    # add item
    path('add',views.CreateItem.as_view(),name='create_item'),
    # edit
    path('update/<int:id>/',views.update_item,name='update_item'),
    # delete
    path('delete/<int:id>/',views.delete_item,name='delete_item'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
]

urlpatterns += [
    # ... the rest of your URLconf goes here...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default="https://www.melbournefoodandwine.com.au/image-tools.php?w=560&h=440&src=/recipes/recipe-placeholder.jpg")
    
    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk":self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User 

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_price','item_desc','item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta():
        model = User
        fields = ['username','email','password1','password2']

food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# Create your views here.

'''Function based view of index
def index(request):
    item_list = Item.objects.all()
    context = {
        'item_list':item_list,
    }
    return render(request,'food/index.html',context) 
    '''

class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'


def item(request):
    return HttpResponse('<h1>This is an item view</h1>')

''' Function based view of detail
def detale(request,item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item':item,
    }
    return render(request,'food/detail.html',context)
'''
class DetaleClassView(DetailView):
    model = Item
    template_name = 'food/detail.html'    

''' Function based view of create item
def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request,'food/item-form.html',{'form':form})
    '''

class CreateItem(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'food/item-form.html'

    def form_valid(self,form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)

def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/item-form.html',{'form':form,'item':item})

def delete_item(request,id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')

    return render(request,'food/item-delete.html',{'item':item})

users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'welcome {username}, your account has been created')
            return redirect('login')
    else:
        form = RegisterForm()

    return render(request,'users/register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">FoodAPP</a>
        <div class="navbar">
            <a class="nav-item nav-link" href="{% url 'food:index'%}">View Item</a>
            <a class="nav-item nav-link" href="#">Delet Item</a>
            <a class="nav-item nav-link" href="{% url 'food:create_item' %}">Add Item</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">Log out</a>
                <a href="{% url 'profile' %}">Profile</a>
            {% else %}
                <a href="{% url 'login' %}">log in</a>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% block body %} 
    {% endblock %}    
</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-5 ">
            <img class="card" height="250px" src="{{ item.item_image }}"/>
        </div>
        <div class="col-md-5">
            <h3>{{ item.item_name }}</h3>
            <h5>{{ item.item_desc }}</h5>
            <h6>${{ item.item_price }}</h6>  
            <h6>{{ item.user_name }}</h6>  
            <a class="btn btn-success" href="{% url 'food:index' %}">Back</a>
            <a class="btn btn-success" href="{% url 'food:update_item' item.id%}">Update</a>       
            <a class="btn btn-danger" href="{% url 'food:delete_item' item.id%}">Delete</a>            
        </div>
    </div>
</div>
{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html'%}

    {% block body %}
    <div class="container-fluid">
        <div class="row" style="text-align: center;">
            {% for item in item_list %}         
            <div class="col-xs-6 col-sm-4 col-md-3 col-lg-3 thumb">
                <div class="card" style="width: auto; margin: auto; padding: 10px;">
                    <img class="card-img-top" src="{{ item.item_image }}"/>
                    <div class="card-body">
                        <h3>{{ item.item_name }}</h3>
                        <h5>{{ item.item_desc }}</h5>
                        <h6>${{ item.item_price }}</h6> 
                        <h6>{{ item.user_name }}</h6>
                        <a class="btn btn-success" href="{% url 'food:detail' item.id %}">Details</a>
                    </div>  
                </div>
            </div>  
            {% endfor %}
        </div>
    </div>  
    {% endblock %}   
    
</body>
</html>

food/templates/food/item-delete.html
{% extends 'food/base.html'%}
{% block body%}
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }}</h2>
    <button type="submit">Confirm</button>
</form>
{% endblock%}

food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}

<div class="conteiner">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Add Item
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                <br>{{ field }}
                            </div>
                        {% endfor %}
                        <button class="btn-info" type="submit">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock%}

users/templates/users/login.html
{% extends 'food/base.html' %}
{% block body %}

<div class="conteiner">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                <br>{{ field }}
                            </div>
                        {% endfor %}
                        <button class="btn-info" type="submit">Log in</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock%}

users/templates/users/logout.html
<h1>You have been Logged out</h1>

users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img width="100px" height="100px" src="{{user.profile.image.url}}">

users/templates/users/register.html
{% extends 'food/base.html' %}
{% block body %}

<div class="conteiner">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Registration
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                <br>{{ field }}
                            </div>
                        {% endfor %}
                        <button class="btn-info" type="submit">Sing up</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock%}